name: GitHub Actions Build and Deploy

on:
  push:
    branches:
      - release

jobs:
  build-and-deploy:
    name: deploy-to-github
    runs-on: ubuntu-latest
    steps:
    - name: Checkout codes from origin/release branch
      uses: actions/checkout@master
    
    - name: Build & deploy
      uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_ADMIN_TOKEN }}
        BASE_BRANCH: release
        BRANCH: gh-pages
        FOLDER: dist
        BUILD_SCRIPT: npm install && npm run build
